const SUPABASE_URL='https://jjrsbbgnqfiezhokxbqz.supabase.co';
const SUPABASE_KEY='sb_publishable_8LlV4bOH3d_axQBQLlHVkA_arQl6nu-';
const headers={apikey:SUPABASE_KEY,Accept:'application/json'};
const esc=(value='')=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const absolute=(value,base)=>{if(!value)return'';try{return new URL(value,base).href}catch{return''}};
async function rows(){const response=await fetch(`${SUPABASE_URL}/rest/v1/obras?published=eq.true&archived=eq.false&show_in_obras_index=eq.true&select=id,slug,title,eyebrow,excerpt,location_public,work_type,hero_image_url,hero_image_alt,show_in_menu,menu_label,sort_order&order=sort_order.asc`,{headers});if(!response.ok)throw new Error(`Supabase ${response.status}`);return response.json();}
async function qrTarget(slug){const response=await fetch(`${SUPABASE_URL}/rest/v1/obras?slug=eq.${encodeURIComponent(slug)}&published=eq.true&archived=eq.false&select=slug,qr_campaign&limit=1`,{headers});if(!response.ok)throw new Error(`Supabase ${response.status}`);const data=await response.json();return data?.[0]||null;}
function siteBase(request){const url=new URL(request.url);const marker='/obras';const index=url.pathname.toLowerCase().indexOf(marker);const basePath=index>=0?url.pathname.slice(0,index+1):'/';return new URL(basePath,url.origin);}
function obraHref(base,slug){const url=new URL('obras/',base);url.searchParams.set('obra',slug);return url.href;}
function menuLinks(items,base){return items.filter(item=>item.show_in_menu).map(item=>`<a href="${esc(obraHref(base,item.slug))}">${esc(item.menu_label||item.title)}</a>`).join('');}
function render(items,base){const hasContent=items.length>0,extraMenu=menuLinks(items,base),robots=hasContent?'index,follow,max-image-preview:large':'noindex,follow';const cards=hasContent?items.map(item=>`<a class="obra-index-card obra-reveal" href="${esc(obraHref(base,item.slug))}"><div class="obra-index-card__media">${item.hero_image_url?`<img src="${esc(absolute(item.hero_image_url,base))}" alt="${esc(item.hero_image_alt||item.title)}" loading="lazy">`:''}</div><div class="obra-index-card__copy"><span>${esc(item.location_public||item.work_type||item.eyebrow||'Obra AZO')}</span><h2>${esc(item.title)}</h2>${item.excerpt?`<p>${esc(item.excerpt)}</p>`:''}</div></a>`).join(''):`<div class="panel" style="grid-column:1/-1"><div class="eyebrow">Em breve</div><h2 class="section-title" style="font-size:clamp(2.6rem,5vw,5rem)">Novas obras serão apresentadas aqui.</h2><p class="section-copy">Enquanto isso, conheça os projetos e serviços da AZO.</p></div>`;const site=path=>new URL(String(path||'').replace(/^\/+/,''),base).href;return`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#0d2f35"><title>Obras AZO | Arquitetura e Construção</title><meta name="description" content="Acompanhe obras da AZO e conheça decisões de arquitetura, interiores e execução que transformam projeto em espaço construído."><meta name="robots" content="${robots}"><link rel="canonical" href="${esc(site('obras/'))}"><link rel="stylesheet" href="${esc(site('assets/css/site.css'))}"><link rel="stylesheet" href="${esc(site('assets/css/obra-page.css'))}"></head><body class="obra-page"><header class="site-header"><a class="brand" href="${esc(site(''))}" aria-label="AZO — início"><img src="${esc(site('assets/images/logo-azo.png'))}" alt="AZO Criação & Construção"></a><nav class="nav"><a href="${esc(site('servicos.html'))}">Serviços</a><a href="${esc(site('projetos.html'))}">Projetos</a>${extraMenu}<a href="${esc(site('index.html#metodo'))}">Como trabalhamos</a><a href="${esc(site('sobre.html'))}">Sobre</a><a class="nav-cta" href="${esc(site('contato.html'))}">Solicitar orçamento</a></nav></header><main><section class="obra-index-hero"><div class="wrap"><div class="eyebrow">Obras AZO</div><h1>Do desenho<br>ao espaço real.</h1><p>Obras apresentadas com contexto, decisões e detalhes.</p></div></section><section><div class="wrap obra-index-grid">${cards}</div></section></main><script src="${esc(site('assets/js/obra-page.js'))}" defer></script></body></html>`;}
export async function onRequest(context){const requestUrl=new URL(context.request.url);const base=siteBase(context.request);const qrSlug=String(requestUrl.searchParams.get('q')||'').trim().toLowerCase();if(qrSlug&&/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(qrSlug)){try{const target=await qrTarget(qrSlug);if(target){const clean=new URL(`obras/${encodeURIComponent(target.slug)}/`,base);clean.searchParams.set('utm_source','qr');clean.searchParams.set('utm_medium','offline');clean.searchParams.set('utm_campaign',target.qr_campaign||target.slug);return Response.redirect(clean.href,302);}}catch{} }
const requestedSlug=String(requestUrl.searchParams.get('obra')||'').trim().toLowerCase();if(requestedSlug&&/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(requestedSlug)){const clean=new URL(`obras/${encodeURIComponent(requestedSlug)}/`,base);return Response.redirect(clean.href,302);}try{const items=await rows();return new Response(render(items||[],base),{headers:{'content-type':'text/html; charset=UTF-8','cache-control':'public, max-age=120, s-maxage=300, stale-while-revalidate=900','x-content-type-options':'nosniff','referrer-policy':'strict-origin-when-cross-origin'}});}catch{return new Response('Temporariamente indisponível.',{status:503,headers:{'content-type':'text/plain; charset=UTF-8','cache-control':'no-store','x-content-type-options':'nosniff'}});}}
