import { supabase, authReady } from '../assets/js/supabase-config.js';

const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
const BUCKET='azo-media';
const PUBLIC_ROOT='/conteudos/';
const state={posts:[],categories:[],projects:[],filter:'all',search:'',current:null,blocks:[],originalSlug:'',originalStatus:'draft',saveTimer:0,saving:false,pendingSave:false,dirty:false,user:null};
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slugify=(v='')=>String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,150);
const uid=()=>crypto.randomUUID();
const nowIso=()=>new Date().toISOString();
const postUrl=post=>`${location.origin}${PUBLIC_ROOT}${encodeURIComponent(post?.slug||'')}/`;
const blockLabels={paragraph:'Texto',h2:'Título H2',h3:'Título H3',image:'Imagem',gallery:'Galeria',list:'Lista',quote:'Citação',highlight:'Destaque',faq:'FAQ',cta:'CTA',table:'Tabela',related_projects:'Projetos relacionados',related_service:'Serviço relacionado',separator:'Separador'};
const statusLabels={draft:'Rascunho',review:'Em revisão',scheduled:'Agendado',published:'Publicado',archived:'Arquivado'};

function toast(message,type='success'){
  const stack=$('#toast-stack');
  if(!stack)return;
  const el=document.createElement('div');el.className=`toast ${type}`;el.innerHTML=`<b>${type==='error'?'!':'✓'}</b><span>${esc(message)}</span>`;stack.appendChild(el);setTimeout(()=>el.remove(),3600);
}
function setSaveState(text='Salvo',kind=''){
  const el=$('#blog-save-state');if(!el)return;el.className=`blog-save-state ${kind}`;el.innerHTML=`<i></i><span>${esc(text)}</span>`;
}
function installCss(){if($('link[data-blog-css]'))return;const link=document.createElement('link');link.rel='stylesheet';link.href='content-blog.css?v=20260810-1';link.dataset.blogCss='1';document.head.appendChild(link);}

function injectUi(){
  installCss();
  const securityButton=$('.sidebar-nav [data-view="security"]');
  if(securityButton&&!$('.sidebar-nav [data-view="blog"]')){
    const button=document.createElement('button');button.className='nav-item';button.dataset.view='blog';button.innerHTML='<i>▤</i><span>Conteúdos</span>';securityButton.before(button);button.addEventListener('click',openBlog);
  }
  const stats=$('#dashboard-stats');
  if(stats&&!$('#stat-blog')) stats.insertAdjacentHTML('beforeend','<article class="stat-card"><span>Conteúdos publicados</span><strong id="stat-blog">—</strong><small id="stat-blog-drafts">carregando...</small></article>');
  const quick=$('.quick-grid');
  if(quick&&!quick.querySelector('[data-blog-quick]')){
    const button=document.createElement('button');button.dataset.blogQuick='1';button.innerHTML='<b>▤</b><span><strong>Conteúdos</strong><small>Crie artigos para o site e SEO</small></span><i>→</i>';button.addEventListener('click',openBlog);quick.appendChild(button);
  }
  if(!$('#view-blog')){
    const view=document.createElement('div');view.className='view';view.id='view-blog';view.innerHTML=`
      <div class="blog-shell">
        <section class="blog-list-screen" id="blog-list-screen">
          <div class="panel blog-toolbar"><div class="blog-search"><span>⌕</span><input id="blog-search" type="search" placeholder="Buscar título, URL ou categoria..."></div><div class="blog-filter-row" id="blog-filters"><button class="blog-filter active" data-blog-filter="all">Todos</button><button class="blog-filter" data-blog-filter="published">Publicados</button><button class="blog-filter" data-blog-filter="draft">Rascunhos</button><button class="blog-filter" data-blog-filter="review">Em revisão</button><button class="blog-filter" data-blog-filter="scheduled">Agendados</button><button class="blog-filter" data-blog-filter="archived">Arquivados</button></div><span class="blog-count" id="blog-count">—</span><button class="btn btn-primary" id="blog-new">+ Novo conteúdo</button></div>
          <div class="blog-list" id="blog-list"><div class="blog-empty"><b>Carregando conteúdos…</b>Sincronizando com o Supabase.</div></div>
        </section>
        <section class="blog-editor" id="blog-editor">
          <div class="blog-editor-bar"><button class="btn btn-ghost" id="blog-back">← Conteúdos</button><div class="blog-save-state" id="blog-save-state"><i></i><span>Salvo</span></div><div class="spacer"></div><button class="btn btn-ghost" id="blog-history-button">Histórico</button><button class="btn btn-ghost" id="blog-preview">Preview</button><button class="btn btn-ghost" id="blog-save">Salvar</button><button class="btn btn-primary" id="blog-publish">Publicar</button></div>
          <div class="blog-editor-layout"><div class="blog-writing"><textarea id="blog-title" class="blog-title-input" rows="2" placeholder="Título do conteúdo"></textarea><textarea id="blog-excerpt" class="blog-excerpt-input" placeholder="Resumo / linha fina. Explique em poucas linhas o que o leitor vai encontrar."></textarea><div class="blog-writing-meta"><span id="blog-word-count">0 palavras</span><span id="blog-read-time">1 min de leitura</span><span id="blog-block-count">0 blocos</span></div><div class="blog-blocks" id="blog-blocks"></div><div class="blog-add"><span class="blog-add-label">Adicionar bloco</span>${['paragraph','h2','h3','image','gallery','list','quote','highlight','faq','cta','table','related_projects','related_service','separator'].map(t=>`<button type="button" data-add-block="${t}">${blockLabels[t]}</button>`).join('')}</div></div>
          <aside class="blog-settings">
            <div class="blog-setting"><h4>Publicação</h4><label>Status</label><select id="blog-status"><option value="draft">Rascunho</option><option value="review">Em revisão</option><option value="published">Publicado</option><option value="scheduled">Agendado</option><option value="archived">Arquivado</option></select><label>Agendar para</label><input id="blog-scheduled" type="datetime-local"><small>Ao chegar a data, o conteúdo passa a ser público automaticamente pela regra do backend.</small></div>
            <div class="blog-setting"><h4>Organização</h4><label>Categoria</label><select id="blog-category"></select><label>Objetivo</label><select id="blog-goal"><option value="">Não definido</option><option value="inform">Informar</option><option value="compare">Comparar</option><option value="answer">Tirar dúvida</option><option value="support_service">Apoiar serviço</option></select><label>Tema principal</label><input id="blog-topic" placeholder="Ex.: projeto arquitetônico em Sorocaba"></div>
            <div class="blog-setting"><h4>Imagem de capa</h4><div class="blog-cover" id="blog-cover"><span>Clique para enviar a capa</span><input id="blog-cover-file" type="file" accept="image/*"></div><label>Texto alternativo</label><input id="blog-cover-alt" placeholder="Descreva a imagem"><div class="blog-block-row"><div><label>Foco horizontal</label><input id="blog-focal-x" type="range" min="0" max="100" value="50"></div><div><label>Foco vertical</label><input id="blog-focal-y" type="range" min="0" max="100" value="50"></div></div></div>
            <div class="blog-setting"><h4>URL</h4><label>Slug</label><input id="blog-slug" placeholder="url-do-conteudo"><div class="blog-url-preview" id="blog-url-preview">/conteudos/</div></div>
            <div class="blog-setting"><h4>Busca & compartilhamento</h4><label>Título para o Google</label><input id="blog-seo-title" maxlength="90"><div class="blog-counter"><span>Recomendação editorial</span><b id="blog-seo-title-count">0</b></div><label>Descrição</label><textarea id="blog-seo-description" maxlength="220"></textarea><div class="blog-counter"><span>Descrição de busca</span><b id="blog-seo-description-count">0</b></div><label>Canonical opcional</label><input id="blog-canonical" placeholder="Automático se vazio"><div class="blog-google"><div class="url" id="blog-google-url">azocc.com.br › conteudos</div><div class="title" id="blog-google-title">Título do conteúdo</div><div class="desc" id="blog-google-desc">Descrição do conteúdo para o Google.</div></div></div>
            <div class="blog-setting"><h4>Serviços relacionados</h4><div class="blog-related-grid"><label><input type="checkbox" data-related-service="projeto-arquitetonico">Projeto arquitetônico</label><label><input type="checkbox" data-related-service="interiores">Interiores</label><label><input type="checkbox" data-related-service="gestao-de-obras">Gestão de obras</label></div></div>
            <div class="blog-setting"><h4>Projetos relacionados</h4><div class="blog-related-grid" id="blog-related-projects"><small>Carregando projetos…</small></div></div>
            <div class="blog-setting"><h4>Checklist</h4><div class="blog-checklist" id="blog-checklist"></div></div>
          </aside></div>
        </section>
      </div>`;
    const security=$('#view-security');security?.before(view);
  }
  if(!$('#blog-preview-modal')){
    document.body.insertAdjacentHTML('beforeend','<div class="blog-preview-modal" id="blog-preview-modal"><div class="blog-preview-frame"><div class="blog-preview-head"><strong>Preview do conteúdo</strong><span id="blog-preview-label"></span><div class="spacer"></div><button class="btn btn-ghost" id="blog-preview-close">Fechar</button></div><iframe id="blog-preview-frame" title="Prévia do conteúdo"></iframe></div></div>');
  }
}

function openBlog(){
  $$('.nav-item[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view==='blog'));
  $$('.view').forEach(v=>v.classList.toggle('active',v.id==='view-blog'));
  $('#view-kicker').textContent='Biblioteca editorial';$('#view-title').textContent='Conteúdos';$('#app-shell')?.classList.remove('menu-open');
  showList();loadAll();
}
function showList(){clearTimeout(state.saveTimer);$('#blog-list-screen')?.classList.remove('hidden');$('#blog-editor')?.classList.remove('open');}
function showEditor(){ $('#blog-list-screen')?.classList.add('hidden');$('#blog-editor')?.classList.add('open');window.scrollTo({top:0,behavior:'smooth'});}

async function ensureSession(){await authReady;const {data}=await supabase.auth.getSession();state.user=data.session?.user||null;if(!state.user)throw new Error('Sessão administrativa não encontrada.');}
async function loadAll(){
  try{
    await ensureSession();
    const [postsRes,categoriesRes,settingsRes,projectsRes]=await Promise.all([
      supabase.from('content_posts').select('*,content_categories(id,name,slug)').order('updated_at',{ascending:false}),
      supabase.from('content_categories').select('*').order('sort_order',{ascending:true}),
      supabase.from('project_settings').select('id,builtin_key,title,published').order('sort_order',{ascending:true}),
      supabase.from('projects').select('id,title,published').order('sort_order',{ascending:true})
    ]);
    if(postsRes.error)throw postsRes.error;if(categoriesRes.error)throw categoriesRes.error;
    state.posts=postsRes.data||[];state.categories=categoriesRes.data||[];
    state.projects=[...(settingsRes.data||[]).map(p=>({key:p.builtin_key||p.id,title:p.title||`Casa ${p.builtin_key}`,published:p.published!==false})),...(projectsRes.data||[]).map(p=>({key:p.id,title:p.title,published:p.published!==false}))].filter(p=>p.published);
    renderList();renderCategoryOptions();renderProjectOptions();updateDashboard();
  }catch(error){$('#blog-list').innerHTML=`<div class="blog-empty"><b>Não foi possível carregar.</b>${esc(error.message)}</div>`;}
}
function effectiveStatus(post){if(post.status==='scheduled')return'scheduled';if(post.status==='published'&&post.published_at&&new Date(post.published_at)>new Date())return'scheduled';return post.status||'draft';}
function seoGood(post){return Boolean(post.title&&post.slug&&post.seo_title&&post.seo_description&&post.cover_url&&post.cover_alt);}
function filteredPosts(){const q=state.search.trim().toLowerCase();return state.posts.filter(post=>{const status=effectiveStatus(post);if(state.filter!=='all'&&status!==state.filter)return false;if(!q)return true;return [post.title,post.slug,post.excerpt,post.content_categories?.name].some(v=>String(v||'').toLowerCase().includes(q));});}
function renderList(){
  const root=$('#blog-list');if(!root)return;const posts=filteredPosts();$('#blog-count').textContent=`${posts.length} ${posts.length===1?'conteúdo':'conteúdos'}`;
  if(!posts.length){root.innerHTML='<div class="blog-empty"><b>Nenhum conteúdo encontrado.</b>Crie um novo artigo ou ajuste os filtros.</div>';return;}
  root.innerHTML=posts.map(post=>{const status=effectiveStatus(post);const date=new Date(post.updated_at||post.created_at).toLocaleDateString('pt-BR');return `<article class="blog-row"><div class="blog-thumb">${post.cover_url?`<img src="${esc(post.cover_url)}" alt="">`:''}</div><div class="blog-main"><strong>${esc(post.title||'Sem título')}</strong><small>/conteudos/${esc(post.slug)}/</small></div><div class="blog-cell">${esc(post.content_categories?.name||'Sem categoria')}</div><div class="blog-cell"><span class="blog-seo ${seoGood(post)?'good':'warn'}">${seoGood(post)?'● Bom':'● Revisar'}</span></div><div class="blog-cell"><span class="blog-status ${status}">${statusLabels[status]||status}</span><small style="display:block;margin-top:5px">${date}</small></div><div class="blog-actions"><button class="blog-icon" data-edit-post="${post.id}" title="Editar">✎</button><a class="blog-icon" href="${PUBLIC_ROOT}${encodeURIComponent(post.slug)}/" target="_blank" title="Abrir">↗</a><button class="blog-icon" data-more-post="${post.id}" title="Mais ações">⋯</button></div></article>`;}).join('');
  $$('[data-edit-post]',root).forEach(b=>b.addEventListener('click',()=>openPost(b.dataset.editPost)));
  $$('[data-more-post]',root).forEach(b=>b.addEventListener('click',()=>postActions(b.dataset.morePost)));
}
function updateDashboard(){const published=state.posts.filter(p=>effectiveStatus(p)==='published').length;const drafts=state.posts.filter(p=>['draft','review'].includes(effectiveStatus(p))).length;if($('#stat-blog'))$('#stat-blog').textContent=published;if($('#stat-blog-drafts'))$('#stat-blog-drafts').textContent=`${drafts} ${drafts===1?'rascunho':'rascunhos'}`;}
function renderCategoryOptions(){const select=$('#blog-category');if(!select)return;select.innerHTML='<option value="">Sem categoria</option>'+state.categories.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')+'<option value="__new">+ Criar categoria</option>';}
function renderProjectOptions(){const root=$('#blog-related-projects');if(!root)return;root.innerHTML=state.projects.length?state.projects.map(p=>`<label><input type="checkbox" data-related-project="${esc(p.key)}">${esc(p.title)}</label>`).join(''):'<small>Nenhum projeto disponível.</small>';}

function emptyBlock(type){const base={id:uid(),block_type:type,sort_order:(state.blocks.length+1)*100,data:{}};switch(type){case'paragraph':case'h2':case'h3':case'quote':case'highlight':base.data={text:''};break;case'image':base.data={url:'',storage_path:'',alt:'',caption:''};break;case'gallery':base.data={images:[]};break;case'list':base.data={items:['']};break;case'faq':base.data={items:[{question:'',answer:''}]};break;case'cta':base.data={title:'',text:'',label:'Solicitar uma conversa',href:'/contato.html'};break;case'table':base.data={headers:['Coluna 1','Coluna 2'],rows:[['','']]};break;case'related_projects':base.data={keys:[]};break;case'related_service':base.data={key:'projeto-arquitetonico'};break;}return base;}
function wordStats(){const text=[state.current?.title,state.current?.excerpt,...state.blocks.map(b=>JSON.stringify(b.data||{}))].join(' ');const count=text.trim()?text.trim().split(/\s+/).length:0;$('#blog-word-count').textContent=`${count} ${count===1?'palavra':'palavras'}`;$('#blog-read-time').textContent=`${Math.max(1,Math.ceil(count/210))} min de leitura`;$('#blog-block-count').textContent=`${state.blocks.length} ${state.blocks.length===1?'bloco':'blocos'}`;}

function renderBlocks(){
  const root=$('#blog-blocks');if(!root)return;root.innerHTML=state.blocks.map((b,i)=>`<article class="blog-block" data-block-index="${i}"><div class="blog-block-head"><span class="blog-block-type">${esc(blockLabels[b.block_type]||b.block_type)}</span><div class="spacer"></div><button class="blog-mini" data-block-up="${i}" title="Mover para cima">↑</button><button class="blog-mini" data-block-down="${i}" title="Mover para baixo">↓</button><button class="blog-mini" data-block-duplicate="${i}" title="Duplicar">⧉</button><button class="blog-mini" data-block-delete="${i}" title="Excluir">×</button></div>${blockFields(b,i)}</article>`).join('');
  bindBlockEvents();wordStats();updateChecklist();
}
function blockFields(b,i){const d=b.data||{};switch(b.block_type){
  case'paragraph':case'h2':case'h3':case'quote':case'highlight':return `<textarea data-block-field="text" data-i="${i}" placeholder="${b.block_type==='paragraph'?'Escreva o texto…':'Digite o conteúdo…'}">${esc(d.text||'')}</textarea>`;
  case'image':return `${d.url?`<img class="blog-block-preview-img" src="${esc(d.url)}" alt="">`:''}<div class="blog-block-row"><label>Imagem<input type="file" data-block-image="${i}" accept="image/*"></label><label>Alt<input data-block-field="alt" data-i="${i}" value="${esc(d.alt||'')}"></label></div><label>Legenda<input data-block-field="caption" data-i="${i}" value="${esc(d.caption||'')}"></label>`;
  case'gallery':return `<div class="blog-list-items">${(d.images||[]).map((img,n)=>`<div class="blog-list-item"><input value="${esc(img.url||'')}" readonly><button class="blog-mini" data-gallery-remove="${i}:${n}">×</button></div>`).join('')}</div><label>Adicionar imagens<input type="file" data-gallery-image="${i}" accept="image/*" multiple></label>`;
  case'list':return `<div class="blog-list-items">${(d.items||['']).map((item,n)=>`<div class="blog-list-item"><input data-list-item="${i}:${n}" value="${esc(typeof item==='string'?item:item?.text||'')}"><button class="blog-mini" data-list-remove="${i}:${n}">×</button></div>`).join('')}</div><button class="btn btn-ghost" type="button" data-list-add="${i}">+ Item</button>`;
  case'faq':return `<div class="blog-faq-items">${(d.items||[]).map((item,n)=>`<div class="blog-faq-item"><input data-faq-q="${i}:${n}" value="${esc(item.question||'')}" placeholder="Pergunta"><textarea data-faq-a="${i}:${n}" placeholder="Resposta">${esc(item.answer||'')}</textarea><button class="blog-mini" data-faq-remove="${i}:${n}">×</button></div>`).join('')}</div><button class="btn btn-ghost" type="button" data-faq-add="${i}">+ Pergunta</button>`;
  case'cta':return `<div class="blog-block-row"><input data-block-field="title" data-i="${i}" value="${esc(d.title||'')}" placeholder="Título"><input data-block-field="label" data-i="${i}" value="${esc(d.label||'')}" placeholder="Texto do botão"></div><textarea data-block-field="text" data-i="${i}" placeholder="Texto">${esc(d.text||'')}</textarea><input data-block-field="href" data-i="${i}" value="${esc(d.href||'/contato.html')}" placeholder="/contato.html">`;
  case'table':return `<textarea data-table-headers="${i}" placeholder="Cabeçalhos separados por |">${esc((d.headers||[]).join(' | '))}</textarea><textarea data-table-rows="${i}" placeholder="Uma linha por linha; colunas separadas por |">${esc((d.rows||[]).map(r=>r.join(' | ')).join('\n'))}</textarea>`;
  case'related_projects':return `<div class="blog-related-grid">${state.projects.map(p=>`<label><input type="checkbox" data-block-project="${i}:${esc(p.key)}" ${(d.keys||[]).includes(p.key)?'checked':''}>${esc(p.title)}</label>`).join('')}</div>`;
  case'related_service':return `<select data-block-field="key" data-i="${i}"><option value="projeto-arquitetonico" ${d.key==='projeto-arquitetonico'?'selected':''}>Projeto arquitetônico</option><option value="interiores" ${d.key==='interiores'?'selected':''}>Interiores</option><option value="gestao-de-obras" ${d.key==='gestao-de-obras'?'selected':''}>Gestão de obras</option></select>`;
  case'separator':return '<small>Separador visual entre seções.</small>';
  default:return '<small>Bloco sem editor disponível.</small>';
}}
function splitPair(value){const [a,b]=String(value).split(':');return[Number(a),Number(b)];}
function bindBlockEvents(){
  $$('[data-block-field]').forEach(el=>el.addEventListener('input',()=>{state.blocks[Number(el.dataset.i)].data[el.dataset.blockField]=el.value;markDirty();}));
  $$('[data-block-up]').forEach(b=>b.addEventListener('click',()=>moveBlock(Number(b.dataset.blockUp),-1)));$$('[data-block-down]').forEach(b=>b.addEventListener('click',()=>moveBlock(Number(b.dataset.blockDown),1)));$$('[data-block-delete]').forEach(b=>b.addEventListener('click',()=>{state.blocks.splice(Number(b.dataset.blockDelete),1);renderBlocks();markDirty();}));$$('[data-block-duplicate]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.blockDuplicate);const clone=structuredClone(state.blocks[i]);clone.id=uid();state.blocks.splice(i+1,0,clone);renderBlocks();markDirty();}));
  $$('[data-list-item]').forEach(el=>el.addEventListener('input',()=>{const[i,n]=splitPair(el.dataset.listItem);state.blocks[i].data.items[n]=el.value;markDirty();}));$$('[data-list-add]').forEach(b=>b.addEventListener('click',()=>{state.blocks[Number(b.dataset.listAdd)].data.items.push('');renderBlocks();markDirty();}));$$('[data-list-remove]').forEach(b=>b.addEventListener('click',()=>{const[i,n]=splitPair(b.dataset.listRemove);state.blocks[i].data.items.splice(n,1);renderBlocks();markDirty();}));
  $$('[data-faq-q]').forEach(el=>el.addEventListener('input',()=>{const[i,n]=splitPair(el.dataset.faqQ);state.blocks[i].data.items[n].question=el.value;markDirty();}));$$('[data-faq-a]').forEach(el=>el.addEventListener('input',()=>{const[i,n]=splitPair(el.dataset.faqA);state.blocks[i].data.items[n].answer=el.value;markDirty();}));$$('[data-faq-add]').forEach(b=>b.addEventListener('click',()=>{state.blocks[Number(b.dataset.faqAdd)].data.items.push({question:'',answer:''});renderBlocks();markDirty();}));$$('[data-faq-remove]').forEach(b=>b.addEventListener('click',()=>{const[i,n]=splitPair(b.dataset.faqRemove);state.blocks[i].data.items.splice(n,1);renderBlocks();markDirty();}));
  $$('[data-table-headers]').forEach(el=>el.addEventListener('input',()=>{state.blocks[Number(el.dataset.tableHeaders)].data.headers=el.value.split('|').map(v=>v.trim()).filter(Boolean);markDirty();}));$$('[data-table-rows]').forEach(el=>el.addEventListener('input',()=>{state.blocks[Number(el.dataset.tableRows)].data.rows=el.value.split('\n').map(row=>row.split('|').map(v=>v.trim())).filter(r=>r.some(Boolean));markDirty();}));
  $$('[data-block-project]').forEach(el=>el.addEventListener('change',()=>{const sep=el.dataset.blockProject.indexOf(':');const i=Number(el.dataset.blockProject.slice(0,sep)),key=el.dataset.blockProject.slice(sep+1);const keys=new Set(state.blocks[i].data.keys||[]);el.checked?keys.add(key):keys.delete(key);state.blocks[i].data.keys=[...keys];markDirty();}));
  $$('[data-block-image]').forEach(el=>el.addEventListener('change',async()=>{const file=el.files?.[0];if(!file)return;await uploadBlockImage(Number(el.dataset.blockImage),file);el.value='';}));$$('[data-gallery-image]').forEach(el=>el.addEventListener('change',async()=>{const files=[...(el.files||[])];for(const file of files)await uploadGalleryImage(Number(el.dataset.galleryImage),file);el.value='';}));$$('[data-gallery-remove]').forEach(b=>b.addEventListener('click',()=>{const[i,n]=splitPair(b.dataset.galleryRemove);state.blocks[i].data.images.splice(n,1);renderBlocks();markDirty();}));
}
function moveBlock(i,delta){const j=i+delta;if(j<0||j>=state.blocks.length)return;[state.blocks[i],state.blocks[j]]=[state.blocks[j],state.blocks[i]];renderBlocks();markDirty();}

async function optimizeImage(file,maxWidth=2200,quality=.86){
  if(!file.type.startsWith('image/')||file.type==='image/gif')return{blob:file,width:null,height:null,ext:(file.name.split('.').pop()||'bin').toLowerCase()};
  try{const bitmap=await createImageBitmap(file);const scale=Math.min(1,maxWidth/bitmap.width);const width=Math.round(bitmap.width*scale),height=Math.round(bitmap.height*scale);const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;canvas.getContext('2d').drawImage(bitmap,0,0,width,height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/webp',quality));bitmap.close();return{blob:blob||file,width,height,ext:blob?'webp':(file.name.split('.').pop()||'jpg')};}catch(_){return{blob:file,width:null,height:null,ext:(file.name.split('.').pop()||'jpg')};}
}
async function uploadToContent(file,folder='blocks',maxWidth=2200){
  if(!state.current?.id)throw new Error('Salve o conteúdo antes de enviar imagens.');setSaveState('Otimizando imagem…','saving');const optimized=await optimizeImage(file,maxWidth);const path=`content/${state.current.id}/${folder}/${uid()}.${optimized.ext}`;const {error}=await supabase.storage.from(BUCKET).upload(path,optimized.blob,{upsert:false,contentType:optimized.blob.type||file.type,cacheControl:'31536000'});if(error)throw error;const {data}=supabase.storage.from(BUCKET).getPublicUrl(path);return{url:data.publicUrl,storage_path:path,width:optimized.width,height:optimized.height};
}
async function uploadBlockImage(i,file){try{const uploaded=await uploadToContent(file,'blocks');state.blocks[i].data={...state.blocks[i].data,...uploaded,alt:state.blocks[i].data.alt||'',caption:state.blocks[i].data.caption||''};renderBlocks();markDirty();toast('Imagem adicionada ao conteúdo.');}catch(error){toast(error.message,'error');setSaveState('Erro no upload','error');}}
async function uploadGalleryImage(i,file){try{const uploaded=await uploadToContent(file,'gallery');state.blocks[i].data.images=state.blocks[i].data.images||[];state.blocks[i].data.images.push({...uploaded,alt:''});renderBlocks();markDirty();}catch(error){toast(error.message,'error');}}
async function uploadCover(file){try{const uploaded=await uploadToContent(file,'cover',2600);state.current.cover_url=uploaded.url;state.current.cover_storage_path=uploaded.storage_path;state.current.cover_width=uploaded.width;state.current.cover_height=uploaded.height;renderCover();markDirty();toast('Capa atualizada.');}catch(error){toast(error.message,'error');}}
function renderCover(){const root=$('#blog-cover');if(!root)return;const input='<input id="blog-cover-file" type="file" accept="image/*">';root.innerHTML=state.current?.cover_url?`<img src="${esc(state.current.cover_url)}" alt="">${input}`:`<span>Clique para enviar a capa</span>${input}`;$('#blog-cover-file').addEventListener('change',e=>{const file=e.target.files?.[0];if(file)uploadCover(file);});}

async function openPost(id){
  try{await ensureSession();const [postRes,blocksRes]=await Promise.all([supabase.from('content_posts').select('*,content_categories(id,name,slug)').eq('id',id).single(),supabase.from('content_blocks').select('*').eq('post_id',id).order('sort_order',{ascending:true}).order('created_at',{ascending:true})]);if(postRes.error)throw postRes.error;if(blocksRes.error)throw blocksRes.error;state.current=postRes.data;state.blocks=blocksRes.data||[];state.originalSlug=state.current.slug;state.originalStatus=state.current.status;fillEditor();showEditor();}catch(error){toast(error.message,'error');}
}
async function newPost(){
  try{await ensureSession();const id=uid(),slug=`rascunho-${Date.now()}`;const {data,error}=await supabase.from('content_posts').insert({id,title:'',slug,excerpt:'',status:'draft',created_by:state.user.id,updated_by:state.user.id}).select('*').single();if(error)throw error;state.current=data;state.blocks=[];state.originalSlug=slug;state.originalStatus='draft';fillEditor();showEditor();markDirty(false);setSaveState('Novo rascunho');}catch(error){toast(error.message,'error');}
}
function localDateValue(value){if(!value)return'';const d=new Date(value);const off=d.getTimezoneOffset();return new Date(d.getTime()-off*60000).toISOString().slice(0,16);}
function fillEditor(){
  const p=state.current;renderCategoryOptions();renderProjectOptions();$('#blog-title').value=p.title||'';$('#blog-excerpt').value=p.excerpt||'';$('#blog-status').value=p.status||'draft';$('#blog-scheduled').value=localDateValue(p.scheduled_at);$('#blog-category').value=p.category_id||'';$('#blog-goal').value=p.content_goal||'';$('#blog-topic').value=p.primary_topic||'';$('#blog-slug').value=p.slug||'';$('#blog-cover-alt').value=p.cover_alt||'';$('#blog-focal-x').value=p.cover_focal_x??50;$('#blog-focal-y').value=p.cover_focal_y??50;$('#blog-seo-title').value=p.seo_title||'';$('#blog-seo-description').value=p.seo_description||'';$('#blog-canonical').value=p.canonical_url||'';$$('[data-related-service]').forEach(el=>el.checked=(p.related_service_keys||[]).includes(el.dataset.relatedService));$$('[data-related-project]').forEach(el=>el.checked=(p.related_project_keys||[]).includes(el.dataset.relatedProject));renderCover();renderBlocks();updateSeoPreview();state.dirty=false;setSaveState('Salvo');
}
function collectPost(){
  const p={...state.current};p.title=$('#blog-title').value.trim();p.excerpt=$('#blog-excerpt').value.trim();p.status=$('#blog-status').value;p.category_id=$('#blog-category').value||null;p.content_goal=$('#blog-goal').value||null;p.primary_topic=$('#blog-topic').value.trim();let slug=slugify($('#blog-slug').value||p.title||state.current.slug);if(!slug)slug=state.current.slug;p.slug=slug;p.cover_alt=$('#blog-cover-alt').value.trim();p.cover_focal_x=Number($('#blog-focal-x').value||50);p.cover_focal_y=Number($('#blog-focal-y').value||50);p.seo_title=$('#blog-seo-title').value.trim();p.seo_description=$('#blog-seo-description').value.trim();p.canonical_url=$('#blog-canonical').value.trim()||null;p.social_image_url=p.social_image_url||p.cover_url||null;p.related_service_keys=$$('[data-related-service]:checked').map(el=>el.dataset.relatedService);p.related_project_keys=$$('[data-related-project]:checked').map(el=>el.dataset.relatedProject);const scheduled=$('#blog-scheduled').value;p.scheduled_at=scheduled?new Date(scheduled).toISOString():null;p.updated_by=state.user?.id||null;return p;
}
function markDirty(schedule=true){state.dirty=true;wordStats();updateSeoPreview();updateChecklist();setSaveState('Alterações não salvas','saving');clearTimeout(state.saveTimer);if(schedule)state.saveTimer=setTimeout(()=>saveDraft({revision:false,silent:true}),1400);}
async function snapshot(){return{post:collectPost(),blocks:state.blocks.map((b,i)=>({...b,sort_order:(i+1)*100}))};}
async function createRevision(){try{const snap=await snapshot();await supabase.from('content_revisions').insert({post_id:state.current.id,snapshot:snap,created_by:state.user?.id||null});}catch(error){console.warn('[AZO Studio] revisão não salva',error);}}
async function saveDraft({revision=false,silent=false}={}){
  if(!state.current||!state.dirty&&!revision)return;if(state.saving){state.pendingSave=true;return;}state.saving=true;setSaveState('Salvando…','saving');
  try{
    if(revision)await createRevision();const p=collectPost();const oldSlug=state.originalSlug;const oldStatus=state.originalStatus;const payload={title:p.title,slug:p.slug,excerpt:p.excerpt,status:p.status,category_id:p.category_id,cover_url:p.cover_url||null,cover_storage_path:p.cover_storage_path||null,cover_alt:p.cover_alt||'',cover_width:p.cover_width||null,cover_height:p.cover_height||null,cover_focal_x:p.cover_focal_x,cover_focal_y:p.cover_focal_y,seo_title:p.seo_title||'',seo_description:p.seo_description||'',canonical_url:p.canonical_url,social_image_url:p.social_image_url,author_name:p.author_name||'AZO Criação & Construção',content_goal:p.content_goal,primary_topic:p.primary_topic||'',related_project_keys:p.related_project_keys||[],related_service_keys:p.related_service_keys||[],published_at:p.published_at||null,scheduled_at:p.scheduled_at,updated_by:state.user.id};
    const postRes=await supabase.from('content_posts').update(payload).eq('id',state.current.id).select('*,content_categories(id,name,slug)').single();if(postRes.error)throw postRes.error;
    const del=await supabase.from('content_blocks').delete().eq('post_id',state.current.id);if(del.error)throw del.error;
    if(state.blocks.length){const rows=state.blocks.map((b,i)=>({id:b.id||uid(),post_id:state.current.id,block_type:b.block_type,sort_order:(i+1)*100,data:b.data||{}}));const ins=await supabase.from('content_blocks').insert(rows);if(ins.error)throw ins.error;}
    if(oldSlug&&oldSlug!==p.slug&&['published','scheduled'].includes(oldStatus)){await supabase.from('content_redirects').upsert({source_path:`/conteudos/${oldSlug}/`,destination_path:`/conteudos/${p.slug}/`,status_code:301,created_by:state.user.id},{onConflict:'source_path'});}
    state.current=postRes.data;state.originalSlug=p.slug;state.originalStatus=p.status;state.dirty=false;setSaveState('Salvo agora');if(!silent)toast('Conteúdo salvo.');
  }catch(error){setSaveState('Erro ao salvar','error');if(!silent)toast(error.message||'Não foi possível salvar.','error');else console.error(error);}finally{state.saving=false;if(state.pendingSave){state.pendingSave=false;saveDraft({silent:true});}}
}

function updateSeoPreview(){
  if(!state.current)return;const title=$('#blog-seo-title').value.trim()||$('#blog-title').value.trim()||'Título do conteúdo';const desc=$('#blog-seo-description').value.trim()||$('#blog-excerpt').value.trim()||'Descrição do conteúdo para o Google.';const slug=slugify($('#blog-slug').value||$('#blog-title').value)||state.current.slug;$('#blog-seo-title-count').textContent=`${$('#blog-seo-title').value.length} caracteres`;$('#blog-seo-description-count').textContent=`${$('#blog-seo-description').value.length} caracteres`;$('#blog-url-preview').textContent=`/conteudos/${slug}/`;$('#blog-google-url').textContent=`azocc.com.br › conteudos › ${slug}`;$('#blog-google-title').textContent=title;$('#blog-google-desc').textContent=desc;}
function checklist(){const title=$('#blog-title')?.value.trim(),slug=slugify($('#blog-slug')?.value||title),desc=$('#blog-seo-description')?.value.trim()||$('#blog-excerpt')?.value.trim();return[{ok:Boolean(title),label:'Título principal definido'},{ok:Boolean(slug),label:'URL válida'},{ok:Boolean(desc),label:'Descrição de busca definida'},{ok:Boolean(state.current?.cover_url),label:'Imagem de capa enviada'},{ok:Boolean($('#blog-cover-alt')?.value.trim()),label:'Texto alternativo da capa'},{ok:state.blocks.some(b=>b.block_type==='h2'),label:'Pelo menos um H2 no conteúdo'},{ok:state.blocks.some(b=>['paragraph','list','faq'].includes(b.block_type)),label:'Conteúdo editorial preenchido'},{ok:Boolean($('#blog-seo-title')?.value.trim()),label:'Título para o Google configurado'},{ok:$$('[data-related-service]:checked').length>0||state.blocks.some(b=>b.block_type==='cta'),label:'Ligação com serviço ou CTA'}];}
function updateChecklist(){const root=$('#blog-checklist');if(!root)return;root.innerHTML=checklist().map(i=>`<div class="blog-check ${i.ok?'ok':''}"><i>${i.ok?'✓':'!'}</i><span>${esc(i.label)}</span></div>`).join('');}

async function publish(){
  if(!state.current)return;const p=collectPost();const required=checklist().slice(0,5);const missing=required.filter(i=>!i.ok);if(missing.length&&!confirm(`Ainda há ${missing.length} item(ns) importante(s) para revisar. Deseja publicar mesmo assim?`))return;
  const scheduled=$('#blog-scheduled').value;if(p.status==='scheduled'||scheduled&&new Date(scheduled)>new Date()){ $('#blog-status').value='scheduled';state.current.status='scheduled';state.current.scheduled_at=scheduled?new Date(scheduled).toISOString():state.current.scheduled_at; }else{ $('#blog-status').value='published';state.current.status='published';state.current.published_at=state.current.published_at||nowIso();state.current.scheduled_at=null; }
  markDirty(false);await saveDraft({revision:true,silent:false});if(!state.dirty){toast(effectiveStatus(state.current)==='scheduled'?'Conteúdo agendado.':'Conteúdo publicado.');window.open(postUrl(state.current),'_blank','noopener');await loadAll();}
}

function previewHtml(){
  const p=collectPost(),title=esc(p.title||'Conteúdo sem título'),excerpt=esc(p.excerpt||'');const blocks=state.blocks.map(previewBlock).join('');return `<!doctype html><html><head><meta charset="utf-8"><base href="${location.origin}/"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="assets/css/site.css"><link rel="stylesheet" href="assets/css/conteudos.css"><style>.site-header{position:absolute}.content-page .loader,.content-page .page-transition{display:none!important}</style></head><body class="content-page"><header class="site-header"><a class="brand"><img src="assets/images/logo-azo.png" alt="AZO"></a><nav class="nav"><a>Serviços</a><a>Projetos</a><a>Como trabalhamos</a><a class="active">Conteúdos</a><a>Sobre</a><a class="nav-cta">Solicitar orçamento</a></nav></header><main><article><header class="article-hero"><div class="wrap"><div class="article-kicker"><span>${esc(state.categories.find(c=>c.id===p.category_id)?.name||'Conteúdo')}</span></div><h1>${title}</h1><p class="article-deck">${excerpt}</p><div class="article-meta"><span>Preview</span><span>·</span><span>AZO Criação & Construção</span></div></div></header>${p.cover_url?`<figure class="article-cover"><img src="${esc(p.cover_url)}" alt="${esc(p.cover_alt||p.title)}" style="object-position:${p.cover_focal_x}% ${p.cover_focal_y}%"></figure>`:''}<div class="article-layout"><div></div><div class="article-body">${blocks}</div></div></article></main><script src="assets/js/conteudos-public.js"></script></body></html>`;}
function previewBlock(b){const d=b.data||{};switch(b.block_type){case'paragraph':return`<p>${esc(d.text||'')}</p>`;case'h2':return`<h2>${esc(d.text||'')}</h2>`;case'h3':return`<h3>${esc(d.text||'')}</h3>`;case'image':return d.url?`<figure class="article-image"><img src="${esc(d.url)}" alt="${esc(d.alt||'')}">${d.caption?`<figcaption>${esc(d.caption)}</figcaption>`:''}</figure>`:'';case'gallery':return`<div style="display:grid;grid-template-columns:repeat(2,1fr);gap:12px;margin:44px 0">${(d.images||[]).map(i=>`<img src="${esc(i.url)}" style="width:100%;border-radius:18px">`).join('')}</div>`;case'list':return`<ul>${(d.items||[]).map(i=>`<li>${esc(i)}</li>`).join('')}</ul>`;case'quote':return`<blockquote class="article-quote">${esc(d.text||'')}</blockquote>`;case'highlight':return`<aside class="article-highlight"><p>${esc(d.text||'')}</p></aside>`;case'faq':return`<div class="article-faq">${(d.items||[]).map(i=>`<details open><summary>${esc(i.question||'')}</summary><p>${esc(i.answer||'')}</p></details>`).join('')}</div>`;case'cta':return`<aside class="article-cta"><h3>${esc(d.title||'Vamos conversar?')}</h3><p>${esc(d.text||'')}</p><a>${esc(d.label||'Solicitar uma conversa')} →</a></aside>`;case'separator':return'<hr>';default:return'';}}
function openPreview(){const modal=$('#blog-preview-modal'),frame=$('#blog-preview-frame');$('#blog-preview-label').textContent=state.current?.slug?`/conteudos/${state.current.slug}/`:'';frame.srcdoc=previewHtml();modal.classList.add('open');}

async function history(){
  if(!state.current)return;const {data,error}=await supabase.from('content_revisions').select('id,created_at,snapshot').eq('post_id',state.current.id).order('created_at',{ascending:false}).limit(20);if(error)return toast(error.message,'error');const modal=$('#blog-preview-modal'),frame=$('#blog-preview-frame');$('#blog-preview-label').textContent='Histórico de revisões';frame.srcdoc=`<!doctype html><html><head><meta charset="utf-8"><style>body{font:14px system-ui;background:#f7f4ee;color:#0d2f35;padding:24px}.row{display:flex;justify-content:space-between;align-items:center;background:#fff;border:1px solid #ddd6ca;border-radius:14px;padding:14px;margin:8px 0}button{border:0;background:#0d2f35;color:#fff;border-radius:999px;padding:9px 13px;cursor:pointer}</style></head><body><h1>Histórico</h1>${(data||[]).map(r=>`<div class="row"><span>${new Date(r.created_at).toLocaleString('pt-BR')}</span><button onclick="parent.postMessage({type:'azo-restore-revision',id:'${r.id}'},'*')">Restaurar</button></div>`).join('')||'<p>Nenhuma revisão ainda.</p>'}</body></html>`;modal.classList.add('open');}
async function restoreRevision(id){const {data,error}=await supabase.from('content_revisions').select('snapshot').eq('id',id).single();if(error)return toast(error.message,'error');const snap=data?.snapshot;if(!snap?.post)return;state.current={...state.current,...snap.post};state.blocks=(snap.blocks||[]).map(b=>({...b,id:b.id||uid()}));fillEditor();markDirty(false);$('#blog-preview-modal').classList.remove('open');toast('Revisão restaurada no editor. Salve para confirmar.');}

async function postActions(id){const post=state.posts.find(p=>p.id===id);if(!post)return;const action=prompt(`Ações para “${post.title||'Sem título'}”:\n1 = Duplicar\n2 = Arquivar\n3 = Despublicar\n4 = Excluir definitivamente`);try{if(action==='1')await duplicatePost(post);if(action==='2')await supabase.from('content_posts').update({status:'archived',updated_by:state.user.id}).eq('id',id);if(action==='3')await supabase.from('content_posts').update({status:'draft',updated_by:state.user.id}).eq('id',id);if(action==='4'&&confirm('Excluir definitivamente este conteúdo?'))await supabase.from('content_posts').delete().eq('id',id);await loadAll();}catch(error){toast(error.message,'error');}}
async function duplicatePost(post){const newId=uid(),newSlug=`${slugify(post.slug||post.title)}-copia-${Date.now().toString().slice(-5)}`;const copy={...post,id:newId,title:`${post.title} — cópia`,slug:newSlug,status:'draft',published_at:null,scheduled_at:null,created_at:undefined,updated_at:undefined,content_categories:undefined,created_by:state.user.id,updated_by:state.user.id};delete copy.created_at;delete copy.updated_at;const {error}=await supabase.from('content_posts').insert(copy);if(error)throw error;const blocks=await supabase.from('content_blocks').select('block_type,sort_order,data').eq('post_id',post.id);if(blocks.error)throw blocks.error;if(blocks.data?.length){const rows=blocks.data.map(b=>({id:uid(),post_id:newId,block_type:b.block_type,sort_order:b.sort_order,data:b.data}));const ins=await supabase.from('content_blocks').insert(rows);if(ins.error)throw ins.error;}toast('Conteúdo duplicado como rascunho.');}

function bindGlobal(){
  $('#blog-new')?.addEventListener('click',newPost);$('#blog-back')?.addEventListener('click',async()=>{if(state.dirty)await saveDraft({silent:true});showList();loadAll();});$('#blog-save')?.addEventListener('click',()=>saveDraft({revision:true,silent:false}));$('#blog-publish')?.addEventListener('click',publish);$('#blog-preview')?.addEventListener('click',openPreview);$('#blog-history-button')?.addEventListener('click',history);$('#blog-preview-close')?.addEventListener('click',()=>$('#blog-preview-modal').classList.remove('open'));
  $('#blog-search')?.addEventListener('input',e=>{state.search=e.target.value;renderList();});$$('[data-blog-filter]').forEach(b=>b.addEventListener('click',()=>{state.filter=b.dataset.blogFilter;$$('[data-blog-filter]').forEach(x=>x.classList.toggle('active',x===b));renderList();}));
  $$('[data-add-block]').forEach(b=>b.addEventListener('click',()=>{state.blocks.push(emptyBlock(b.dataset.addBlock));renderBlocks();markDirty();}));
  ['blog-title','blog-excerpt','blog-status','blog-scheduled','blog-goal','blog-topic','blog-slug','blog-cover-alt','blog-focal-x','blog-focal-y','blog-seo-title','blog-seo-description','blog-canonical'].forEach(id=>$('#'+id)?.addEventListener('input',e=>{if(id==='blog-title'&&($('#blog-slug').value.startsWith('rascunho-')||!$('#blog-slug').value))$('#blog-slug').value=slugify(e.target.value);markDirty();}));
  $('#blog-category')?.addEventListener('change',async e=>{if(e.target.value==='__new'){const name=prompt('Nome da nova categoria:');if(name){const slug=slugify(name);const {data,error}=await supabase.from('content_categories').insert({name,slug,sort_order:100}).select('*').single();if(error)toast(error.message,'error');else{state.categories.push(data);renderCategoryOptions();$('#blog-category').value=data.id;markDirty();}}else{renderCategoryOptions();$('#blog-category').value=state.current?.category_id||'';}}else markDirty();});
  $$('[data-related-service]').forEach(el=>el.addEventListener('change',()=>markDirty()));
  addEventListener('message',e=>{if(e.data?.type==='azo-restore-revision'&&e.data.id)restoreRevision(e.data.id);});
  addEventListener('beforeunload',e=>{if(state.dirty){e.preventDefault();e.returnValue='';}});
}

async function install(){injectUi();bindGlobal();try{await ensureSession();loadAll();}catch(_){}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
